/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordlegame;

import wordlegame.view.WordleGuessingGameGUI;

public class App {

    public static void main(String[] args) {
        WordleGuessingGameGUI view = new WordleGuessingGameGUI();
    }
}
